# Generated by Django 4.2.6 on 2023-12-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('movie', 'movie'), ('book', 'book'), ('music', 'music')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.category'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(choices=[('drama', 'drama'), ('comedy', 'comedy'), ('western', 'western'), ('fantasy', 'fantasy'), ('sci-fi', 'sci-fi'), ('detective', 'detective'), ('thriller', 'thriller'), ('tale', 'tale'), ('gonzo', 'gonzo'), ('roman', 'roman'), ('ballad', 'ballad'), ('rock-n-roll', 'rock-n-roll'), ('classical', 'classical'), ('rock', 'rock'), ('chanson', 'chanson')], through='reviews.GenreTitle', to='reviews.genre'),
        ),
    ]
